/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TotemRouteImport } from './routes/totem'
import { Route as SalaRouteImport } from './routes/sala'
import { Route as HubRouteImport } from './routes/hub'
import { Route as GiocaRouteImport } from './routes/gioca'
import { Route as CucinaRouteImport } from './routes/cucina'
import { Route as CassaRouteImport } from './routes/cassa'
import { Route as CameriereRouteImport } from './routes/cameriere'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const TotemRoute = TotemRouteImport.update({
  id: '/totem',
  path: '/totem',
  getParentRoute: () => rootRouteImport,
} as any)
const SalaRoute = SalaRouteImport.update({
  id: '/sala',
  path: '/sala',
  getParentRoute: () => rootRouteImport,
} as any)
const HubRoute = HubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => rootRouteImport,
} as any)
const GiocaRoute = GiocaRouteImport.update({
  id: '/gioca',
  path: '/gioca',
  getParentRoute: () => rootRouteImport,
} as any)
const CucinaRoute = CucinaRouteImport.update({
  id: '/cucina',
  path: '/cucina',
  getParentRoute: () => rootRouteImport,
} as any)
const CassaRoute = CassaRouteImport.update({
  id: '/cassa',
  path: '/cassa',
  getParentRoute: () => rootRouteImport,
} as any)
const CameriereRoute = CameriereRouteImport.update({
  id: '/cameriere',
  path: '/cameriere',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cameriere': typeof CameriereRoute
  '/cassa': typeof CassaRoute
  '/cucina': typeof CucinaRoute
  '/gioca': typeof GiocaRoute
  '/hub': typeof HubRoute
  '/sala': typeof SalaRoute
  '/totem': typeof TotemRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cameriere': typeof CameriereRoute
  '/cassa': typeof CassaRoute
  '/cucina': typeof CucinaRoute
  '/gioca': typeof GiocaRoute
  '/hub': typeof HubRoute
  '/sala': typeof SalaRoute
  '/totem': typeof TotemRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cameriere': typeof CameriereRoute
  '/cassa': typeof CassaRoute
  '/cucina': typeof CucinaRoute
  '/gioca': typeof GiocaRoute
  '/hub': typeof HubRoute
  '/sala': typeof SalaRoute
  '/totem': typeof TotemRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cameriere'
    | '/cassa'
    | '/cucina'
    | '/gioca'
    | '/hub'
    | '/sala'
    | '/totem'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cameriere'
    | '/cassa'
    | '/cucina'
    | '/gioca'
    | '/hub'
    | '/sala'
    | '/totem'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cameriere'
    | '/cassa'
    | '/cucina'
    | '/gioca'
    | '/hub'
    | '/sala'
    | '/totem'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CameriereRoute: typeof CameriereRoute
  CassaRoute: typeof CassaRoute
  CucinaRoute: typeof CucinaRoute
  GiocaRoute: typeof GiocaRoute
  HubRoute: typeof HubRoute
  SalaRoute: typeof SalaRoute
  TotemRoute: typeof TotemRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/totem': {
      id: '/totem'
      path: '/totem'
      fullPath: '/totem'
      preLoaderRoute: typeof TotemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sala': {
      id: '/sala'
      path: '/sala'
      fullPath: '/sala'
      preLoaderRoute: typeof SalaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub': {
      id: '/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof HubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gioca': {
      id: '/gioca'
      path: '/gioca'
      fullPath: '/gioca'
      preLoaderRoute: typeof GiocaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cucina': {
      id: '/cucina'
      path: '/cucina'
      fullPath: '/cucina'
      preLoaderRoute: typeof CucinaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cassa': {
      id: '/cassa'
      path: '/cassa'
      fullPath: '/cassa'
      preLoaderRoute: typeof CassaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cameriere': {
      id: '/cameriere'
      path: '/cameriere'
      fullPath: '/cameriere'
      preLoaderRoute: typeof CameriereRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CameriereRoute: CameriereRoute,
  CassaRoute: CassaRoute,
  CucinaRoute: CucinaRoute,
  GiocaRoute: GiocaRoute,
  HubRoute: HubRoute,
  SalaRoute: SalaRoute,
  TotemRoute: TotemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
